cfg = dict(
    model='pvlt_tiny',
    pretrain_pth='./preweights/pvt_v1/pvt_tiny.pth',
    # pretrain_pth='',
    drop_path=0.1,
    clip_grad=None,
    output_dir='checkpoints/dws_pvlt_exp1',
    data_set='FashionGen',
    mixup=0,
    cutmix=0,
    input_size=256,
    loss_type={'itm':1, 'mlm':1, 't2i':1, 'cls':0}, # only use itm, mlm, and t2i for pre-training
    batch_size=100, # per GPU
    epochs=5,   # only for debug, please change it
    lr=2.5e-4,
    weight_decay=0.01,
    mask_ratio=0.5, # refer to Simple Masked Image Modeling
    mask_strategy='random_grid',    # random_grid stroke
    mask_patch_size=16,
)